Refactor github action

diff --git a/.github/workflows/enforcer.yaml b/.github/workflows/enforcer.yaml
--- a/.github/workflows/enforcer.yaml
+++ b/.github/workflows/enforcer.yaml
@@ -5,10 +5,11 @@ on:
 
 jobs:
   check_branch:
+    if: github.base_ref == 'dev' && github.head_ref != 'feat/dev-branch-workflow-asdf'
+    name: Throw error for non dev branch into main
     runs-on: ubuntu-latest
     steps:
-      - name: Check branch
-        if: github.base_ref == 'dev' && github.head_ref != 'feat/dev-branch-workflow-asdf'
-        run: |
-          echo "ERROR: You can only merge the dev branch into main."
-          exit 1
+      - name: Throw error
+        run: echo "ERROR You can only merge the dev branch into main."
+      - name: Exit with unsuccessful termination
+        run: exit 1
