Revert "Add temporary debugging"
This reverts commit 841f626391064f752dc579ccdec4248729d8cd80.

diff --git a/.github/workflows/enforcer.yml b/.github/workflows/enforcer.yml
--- a/.github/workflows/enforcer.yml
+++ b/.github/workflows/enforcer.yml
@@ -15,9 +15,5 @@ jobs:
       - name: Check branch
         if: github.base_ref == 'main' && github.head_ref != 'dev'
         run: |
-          echo "Base branch: ${{ github.base_ref }}"
-          echo "Head branch: ${{ github.head_ref }}"
-        # run: |
-        #   echo "ERROR: You can only merge changes into main from the dev branch."
-        #   exit 1
-        #    - name: Debugging Info
+          echo "ERROR: You can only merge changes into main from the dev branch."
+          exit 1
