Change branches that are checked

diff --git a/.github/workflows/enforcer.yaml b/.github/workflows/enforcer.yaml
--- a/.github/workflows/enforcer.yaml
+++ b/.github/workflows/enforcer.yaml
@@ -5,10 +5,10 @@ on:
 
 jobs:
   check_branch:
-    if: github.base_ref == 'dev' && github.head_ref != 'feat/dev-branch-workflow-asdf'
-    name: Check branch
+    if: github.base_ref == 'main' && github.head_ref != 'dev'
+    name: Check dev -> main
     runs-on: ubuntu-latest
     steps:
       - name: Throw error and exit
         run: |
-          echo "ERROR You can only merge the dev branch into main." && exit 1
+          echo "ERROR: You can only merge the dev branch into main." && exit 1
